# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: nonecheck=False
# cython: overflowcheck=False
# cython: initializedcheck=False
# cython: cdivision=True
# cython: auto_pickle=True
# cython: profile=True


cdef extern from *:
    cdef int BOARD_WIDTH = 8
    cdef int BOARD_HEIGHT = 8
    cdef int PLACEABLE_PIECE_COUNT = 5

    cdef int SQUARE_COUNT = BOARD_HEIGHT * BOARD_WIDTH

    cdef int MOVE_PIECE_ACTION_SIZE = BOARD_WIDTH * BOARD_HEIGHT * BOARD_WIDTH * BOARD_HEIGHT
    cdef int PLACE_PAWN_ACTION_SIZE = BOARD_WIDTH * (BOARD_HEIGHT - 2)
    cdef int PLACE_OTHER_PIECE_ACTION_SIZE = BOARD_WIDTH * BOARD_HEIGHT * (PLACEABLE_PIECE_COUNT - 1)
    cdef int PROMOTE_PAWN_CAPTURE_LEFT_ACTION_SIZE = (BOARD_WIDTH - 1) * (PLACEABLE_PIECE_COUNT - 1)
    cdef int PROMOTE_PAWN_MOVE_FORWARD_ACTION_SIZE = BOARD_WIDTH * (PLACEABLE_PIECE_COUNT - 1)
    cdef int PROMOTE_PAWN_CAPTURE_RIGHT_ACTION_SIZE = (BOARD_WIDTH - 1) * (PLACEABLE_PIECE_COUNT - 1)

    cdef int PLACE_PAWN_OFFSET = MOVE_PIECE_ACTION_SIZE
    cdef int PLACE_OTHER_PIECE_OFFSET = PLACE_PAWN_OFFSET + PLACE_PAWN_ACTION_SIZE
    cdef int PROMOTE_PAWN_CAPTURE_LEFT_OFFSET = PLACE_OTHER_PIECE_OFFSET + PLACE_OTHER_PIECE_ACTION_SIZE
    cdef int PROMOTE_PAWN_MOVE_FORWARD_OFFSET = PROMOTE_PAWN_CAPTURE_LEFT_OFFSET + PROMOTE_PAWN_CAPTURE_LEFT_ACTION_SIZE
    cdef int PROMOTE_PAWN_CAPTURE_RIGHT_OFFSET = PROMOTE_PAWN_MOVE_FORWARD_OFFSET + PROMOTE_PAWN_MOVE_FORWARD_ACTION_SIZE

    cdef int ACTION_SIZE = PROMOTE_PAWN_CAPTURE_RIGHT_OFFSET + PROMOTE_PAWN_CAPTURE_RIGHT_ACTION_SIZE


    cdef int KING_W = 0
    cdef int PAWN_W = 1
    cdef int KNIGHT_W = 2
    cdef int BISHOP_W = 3
    cdef int ROOK_W = 4
    cdef int QUEEN_W = 5
    cdef int EMPTY = 6
    cdef int QUEEN_B = 7
    cdef int ROOK_B = 8
    cdef int BISHOP_B = 9
    cdef int KNIGHT_B = 10
    cdef int PAWN_B = 11
    cdef int KING_B = 12

    cdef int PLAYER_WHITE = 1
    cdef int PLAYER_BLACK = -1


    cdef int[16]  KNIGHT_MOVES =   [1,2 ,  2,1 ,  -1,2 ,  -2, 1 ,  1,-2 ,  2, -1 ,  -1, -2 ,  -2, -1]  
    cdef int[16]  KING_MOVES =   [0,1 , 1,1 , 1,0 , 1,-1 , 0,-1 ,  -1,-1 , -1,0 , -1,1 ]

    #max pieces on hand
    cdef int MAX_PAWNS = 16
    cdef int MAX_KNIGHTS = 4
    cdef int MAX_BISHOPS = 4
    cdef int MAX_ROOKS = 4
    cdef int MAX_QUEENS = 2


# Python-level constants that are calculated directly
# These are accessible from Python methods in .pyx files
BOARD_WIDTH_PY = 8
BOARD_HEIGHT_PY = 8
PLACEABLE_PIECE_COUNT_PY = 5

SQUARE_COUNT_PY = BOARD_WIDTH_PY * BOARD_HEIGHT_PY

MOVE_PIECE_ACTION_SIZE_PY = BOARD_WIDTH_PY * BOARD_HEIGHT_PY * BOARD_WIDTH_PY * BOARD_HEIGHT_PY
PLACE_PAWN_ACTION_SIZE_PY = BOARD_WIDTH_PY * (BOARD_HEIGHT_PY - 2)
PLACE_OTHER_PIECE_ACTION_SIZE_PY = BOARD_WIDTH_PY * BOARD_HEIGHT_PY * (PLACEABLE_PIECE_COUNT_PY - 1)
PROMOTE_PAWN_CAPTURE_LEFT_ACTION_SIZE_PY = (BOARD_WIDTH_PY - 1) * (PLACEABLE_PIECE_COUNT_PY - 1)
PROMOTE_PAWN_MOVE_FORWARD_ACTION_SIZE_PY = BOARD_WIDTH_PY * (PLACEABLE_PIECE_COUNT_PY - 1)
PROMOTE_PAWN_CAPTURE_RIGHT_ACTION_SIZE_PY = (BOARD_WIDTH_PY - 1) * (PLACEABLE_PIECE_COUNT_PY - 1)

PLACE_PAWN_OFFSET_PY = MOVE_PIECE_ACTION_SIZE_PY
PLACE_OTHER_PIECE_OFFSET_PY = PLACE_PAWN_OFFSET_PY + PLACE_PAWN_ACTION_SIZE_PY
PROMOTE_PAWN_CAPTURE_LEFT_OFFSET_PY = PLACE_OTHER_PIECE_OFFSET_PY + PLACE_OTHER_PIECE_ACTION_SIZE_PY
PROMOTE_PAWN_MOVE_FORWARD_OFFSET_PY = PROMOTE_PAWN_CAPTURE_LEFT_OFFSET_PY + PROMOTE_PAWN_CAPTURE_LEFT_ACTION_SIZE_PY
PROMOTE_PAWN_CAPTURE_RIGHT_OFFSET_PY = PROMOTE_PAWN_MOVE_FORWARD_OFFSET_PY + PROMOTE_PAWN_MOVE_FORWARD_ACTION_SIZE_PY

ACTION_SIZE_PY = PROMOTE_PAWN_CAPTURE_RIGHT_OFFSET_PY + PROMOTE_PAWN_CAPTURE_RIGHT_ACTION_SIZE_PY

KING_W_PY = 0
PAWN_W_PY = 1
KNIGHT_W_PY = 2
BISHOP_W_PY = 3
ROOK_W_PY = 4
QUEEN_W_PY = 5
EMPTY_PY = 6
QUEEN_B_PY = 7
ROOK_B_PY = 8
BISHOP_B_PY = 9
KNIGHT_B_PY = 10
PAWN_B_PY = 11
KING_B_PY = 12

PLAYER_WHITE_PY = 1
PLAYER_BLACK_PY = -1

KNIGHT_MOVES_PY = [1,2 ,  2,1 ,  -1,2 ,  -2, 1 ,  1,-2 ,  2, -1 ,  -1, -2 ,  -2, -1]
KING_MOVES_PY = [0,1 , 1,1 , 1,0 , 1,-1 , 0,-1 ,  -1,-1 , -1,0 , -1,1]

MAX_PAWNS_PY = 16
MAX_KNIGHTS_PY = 4
MAX_BISHOPS_PY = 4
MAX_ROOKS_PY = 4
MAX_QUEENS_PY = 2
